DATASET:
  TRAIN:
    TYPE: 'Ski2dpose'
    ROOT: './data/ski2dpose/'
    IMG_PREFIX: 'train'
    ANN: 'keypoints_train_no_cog.json'
    AUG:
      FLIP: true
      ROT_FACTOR: 90
      SCALE_FACTOR: 0.35
      NUM_JOINTS_HALF_BODY: 12
      PROB_HALF_BODY: 0.3
  VAL:
    TYPE: 'Ski2dpose'
    ROOT: './data/ski2dpose/'
    IMG_PREFIX: 'val'
    ANN: 'keypoints_val_no_cog.json'
  TEST:
    TYPE: 'Ski2dpose_det'
    ROOT: './data/ski2dpose/'
    IMG_PREFIX: 'val'
    DET_FILE: './exp/json/test_det_yolo.json'
    ANN: 'keypoints_val_no_cog.json'
DATA_PRESET:
  TYPE: 'simple'
  SIGMA: 2
  NUM_JOINTS: 24
  IMAGE_SIZE:
  - 256
  - 192
  HEATMAP_SIZE:
  - 64
  - 48
MODEL:
  TYPE: 'FastPose'
  PRETRAINED: ''
  TRY_LOAD: ''
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 50
LOSS:
  TYPE: 'MSELoss'
DETECTOR:
  NAME: 'yolo'
  CONFIG: 'detector/yolo/cfg/yolov3-spp.cfg'
  WEIGHTS: 'detector/yolo/data/yolov3-spp.weights'
  NMS_THRES: 0.6
  CONFIDENCE: 0.05
TRAIN:
  WORLD_SIZE: 1
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  END_EPOCH: 220
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
  DPG_MILESTONE: 140
  DPG_STEP:
  - 160
  - 190
